fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--diff, --check]

  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: 2.17.4
  #   hooks:
  #   - id: pylint
  #     args: 
  #     - --ignored-modules=scipy.special
  #     - --ignore=C0103,E0611

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 1.3.0
  #   hooks:
  #   - id: mypy
  #     exclude: ^tests/
  #     args: [--strict]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
    - id: pydocstyle
      args:  
      - --ignore=D400,D104,D416,D107,D212,D203
