name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      VIRTUAL_ENV: venv
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          .cache/pip
          venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install virtualenv
      run: |
          python -m pip install --upgrade pip
          pip install virtualenv

    - name: Create virtualenv
      run: |
          virtualenv $VIRTUAL_ENV
          source $VIRTUAL_ENV/bin/activate
          pip install -r requirements.txt
    - uses: pre-commit/action@v3.0.0
